import { userFactory } from '#database/factories/user'

/**
 * This file is used by the `node ace db:seed` command. It is used
 * to seed the database using mock data generated by several factories.
 *
 * This is useful for development and testing, where you often need mock
 * data to run assertions against, or to see some data on the screen.
 */
export async function seed() {
  console.log(`Creating users`)
  await userFactory.createMany(10, 1)

  // Add more factory calls here to seed any other data you need
}
